use clipper2::{EndType, FillRule, JoinType, Paths};

use std::fmt::{self, Write};

use crate::core::{
    PcbLayer, Primitive,
    toolpath::helpers::{arc_to_path, circle_to_path, rectangle_to_path, segment_to_path},
    tools::CncTool,
};

mod helpers;

#[derive(Debug)]
pub enum ToolpathError {
    BuildError(String),
}

impl fmt::Display for ToolpathError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ToolpathError::BuildError(msg) => write!(f, "Build error: {}", msg),
        }
    }
}

impl std::error::Error for ToolpathError {}

#[derive(Debug)]
pub struct ToolpathGenerator {
    pub traces: Paths,
}

impl ToolpathGenerator {
    pub fn new(layer: &PcbLayer, is_outline: bool) -> Result<Self, ToolpathError> {
        log::info!("Build path from layer");
        let mut traces: Vec<Paths> = Vec::new();
        let mut s: Self;

        for trace in &layer.traces {
            for primitive in &trace.primitives {
                traces.push(primitive_to_paths(primitive));
            }
        }

        if traces.len() >= 2 {
            let mut final_clipper = traces[0].to_clipper_subject().add_clip(traces[1].clone());

            for i in 2..traces.len() {
                final_clipper = final_clipper
                    .union(FillRule::default())
                    .map_err(|_| {
                        ToolpathError::BuildError("Failed to execute union operation".into())
                    })?
                    .to_clipper_subject()
                    .add_clip(traces[i].clone());
            }

            s = Self {
                traces: final_clipper.union(FillRule::default()).map_err(|_| {
                    ToolpathError::BuildError("Failed to execute union operation".into())
                })?,
            };
        } else {
            s = Self {
                traces: if traces.len() > 0 {
                    traces[0].clone()
                } else {
                    Default::default()
                },
            };
        }

        if is_outline {
            s.traces = s
                .traces
                .into_iter()
                .filter(|p| p.signed_area() > 0.0)
                .collect();
        }

        Ok(s)
    }

    pub fn generate_toolpaths<Tool: CncTool>(
        &self,
        tool: &Tool,
        depth: f64,
        nb_passes: u32,
        pass_overlap: f64,
    ) -> Vec<Paths> {
        let width = tool.cutting_width(depth);
        let step = width * (1.0 - pass_overlap.min(1.0).max(0.0));

        (0..nb_passes)
            .map(|pass| {
                let offset = (width / 2.0) + (pass as f64) * step;
                self.traces
                    .inflate(offset, JoinType::Round, EndType::Polygon, 2.0)
            })
            .collect::<Vec<Paths>>()
    }
}

pub fn generate_isolation_gcode(
    passes: &Vec<Paths>,
    tool: &dyn CncTool,
    depth: f64,
    z_safe: f64,
    z_finish: f64,
) -> String {
    let mut gcode = String::new();

    // Header GRBL
    writeln!(gcode, "; Generated by CopperCrab").unwrap();
    writeln!(gcode, "; Tool: {}", tool.name()).unwrap();
    writeln!(gcode, "; Depth: {}mm", depth).unwrap();
    writeln!(gcode, "G21 ; mm").unwrap();
    writeln!(gcode, "G90 ; absolute coordinates").unwrap();
    writeln!(gcode, "G17 ; XY plane").unwrap();

    // Go to safe position
    writeln!(gcode, "G0 Z{}", z_safe).unwrap();
    writeln!(gcode, "G0 X0 Y0").unwrap();
    writeln!(gcode, "M3 S{}; Start spindle", tool.spindle_speed()).unwrap();

    for (pass_index, paths) in passes.iter().enumerate() {
        writeln!(gcode, "\n; ========== Pass {} ==========", pass_index + 1).unwrap();

        for path in paths.iter() {
            let mut points = path.iter();

            if let Some(first) = points.next() {
                writeln!(gcode, "; Move to the first point").unwrap();
                writeln!(gcode, "G0 Z{}", z_safe).unwrap();
                writeln!(gcode, "G0 X{:.4} Y{:.4}", first.x(), first.y()).unwrap();

                let mut current_depth = 0.0;

                while current_depth < depth {
                    current_depth = (current_depth + tool.max_depth()).min(depth);

                    writeln!(
                        gcode,
                        "; ----- Depth step {} / {} -----",
                        current_depth, depth
                    )
                    .unwrap();

                    // Plunge
                    writeln!(gcode, "G1 Z{:.4} F{}", -current_depth, tool.plunge_rate()).unwrap();

                    // Follow the path
                    for point in points.as_ref() {
                        writeln!(
                            gcode,
                            "G1 X{:.4} Y{:.4} F{}",
                            point.x(),
                            point.y(),
                            tool.feed_rate()
                        )
                        .unwrap();
                    }

                    // Closing path
                    writeln!(gcode, "G1 X{:.4} Y{:.4}", first.x(), first.y()).unwrap();
                }

                // Go safe Z
                writeln!(gcode, "G0 Z{}", z_safe).unwrap();
            }
        }
    }

    // Footer
    writeln!(gcode, "\n; End of program").unwrap();
    writeln!(gcode, "G0 Z{} ; Go to finish Z", z_finish).unwrap();
    writeln!(gcode, "G0 X0 Y0 ; Go to Zero").unwrap();
    writeln!(gcode, "M5 ; Spindle off").unwrap();
    writeln!(gcode, "M30 ; end").unwrap();

    gcode
}

fn primitive_to_paths(primitive: &Primitive) -> Paths {
    match primitive {
        crate::core::Primitive::Segment(segment) => segment_to_path(segment),
        crate::core::Primitive::Arc(arc) => arc_to_path(arc, 100),
        crate::core::Primitive::Circle(circle) => circle_to_path(circle, 100),
        crate::core::Primitive::Rectangle(rectangle) => rectangle_to_path(rectangle),
    }
}
